# escape=`

FROM lacledeslan/gamesvr-srcds-csgo:linux

LABEL maintainer "Laclede's LAN <contact@lacledeslan.com>"

ENV IMAGE="gamesvr-srcds-csgo-freeplay:linux"

HEALTHCHECK NONE

# UPDATE USERNAME
RUN usermod -l CSGO.Freeplay CSGO

USER CSGO.Freeplay

COPY ./dist /app/bin/

COPY ./dist.linux /app/bin/csgo/

WORKDIR /app/bin/

ENTRYPOINT ["/bin/sh"]
